### ISSUE TITLE
Login not working because of captcha

### ISSUE THREAD

**Issue by lchauvin** [pwrtux/substack_archiver#1]
Unfortunately, I don't think this works anymore because of some captcha when trying to login.

The only was to do this so far, is to use download my cookies from the webbrowser, put them in json format, load them in my python code, and attach them in the get request to the API. Although I think cookies are only valid for 30min, so not the best.

**Comment by pwrtux** [comment]
Thanks for letting me know. I'll look into it. Custom Substack urls are working fine so far.

**Comment by pwrtux** [comment]
Good news! I've addressed the login and captcha issues by porting the Substack Archiver to use Playwright. Here's a summary of the changes:

- By using Playwright, it helps avoid triggering captcha checks.
- Improved reliability: The new version is more robust against changes in the website's structure and security measures.

These changes should resolve the issues you were experiencing. 

Please try the updated version and let me know if you encounter any issues.
